"""ADD: user table

Revision ID: 4d00c9b0516e
Revises: 52b7263bba19
Create Date: 2026-01-04 14:04:33.143440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d00c9b0516e'
down_revision: Union[str, Sequence[str], None] = '52b7263bba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth_day',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'birth_day',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
