"""Edit message table: adding is_edited column

Revision ID: 76159faa56c8
Revises: 0d3f7039ba77
Create Date: 2026-01-20 17:22:23.965106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76159faa56c8'
down_revision: Union[str, Sequence[str], None] = '0d3f7039ba77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_edited', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_edited')
    # ### end Alembic commands ###
