"""EDIT: chat tables

Revision ID: 7a5ccb6859fe
Revises: fd15ec3ae3fb
Create Date: 2026-01-12 14:51:11.514074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5ccb6859fe'
down_revision: Union[str, Sequence[str], None] = 'fd15ec3ae3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
